### ISSUE TITLE
6 across

### ISSUE THREAD

**Issue by JacobLett** [rtpHarry/Bootstrap3-ShowManySlideOneCarousel#5]
Thank you for sharing this. I am trying to get it to work with six across and it works on desktop. But on mobile it is stacking items. Do you know what I would change to hide the stacked items?

http://codepen.io/JacobLett/pen/PGZKZz

**Comment by rtpHarry** [comment]
By "stacking" do you mean its only showing 1 at a time? This is because you have the `col-xs-12` class set which means a single full width column on the xs screen size.

I played around with editing that places where that class was used but it broke the rest so I think you may have changed something else?

Have you tried following [the guide I wrote on the wiki](https://github.com/rtpHarry/Bootstrap3-ShowManySlideOneCarousel/wiki/Change-the-number-of-slides-visible-at-any-one-time)? It goes into detail about how to modify it and how it works.

**Comment by JacobLett** [comment]
I was able to get it to work by using display none on the last two items . Thank you for your help.

http://codepen.io/JacobLett/pen/PGZKZz
