### ISSUE TITLE
Bold bug in transition

### ISSUE THREAD

**Issue by Vitolla** [rtpHarry/Bootstrap3-ShowManySlideOneCarousel#6]
all texts turn bold in a transition

http://imgur.com/WOiB2jC

**Comment by rtpHarry** [comment]
That is strange, I know sometimes when CSS is performing animations the text and images can look slightly different. This is because the system doesn't perform such high quality anti-aliasing while its animating for speed reasons. This is part of the browser though not anything in the css code that can control it.

I don't know if that's what's causing your issue? I'm not sure what else to say sorry.

**Comment by Vitolla** [comment]
I researched a lot, but I also did not find a solution to this problem.
